config/routes.rb
Rails.application.routes.draw do
  resources :originubs
  resources :places do
    collection do
      put :get_locations
    end
  end
  root 'places#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/originub.rb
class Originub < ApplicationRecord
  max_paginates_per 20
end

app/models/place.rb
class Place < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/originubs_controller.rb
class OriginubsController < ApplicationController
  before_action :set_originub, only: [:show, :edit, :update, :destroy]

  # GET /originubs
  # GET /originubs.json
  def index
    @originubs = Originub.all.page(params[:page])
  end

  # GET /originubs/1
  # GET /originubs/1.json
  def show
  end

  # GET /originubs/new
  def new
    @originub = Originub.new
  end

  # GET /originubs/1/edit
  def edit
  end

  # POST /originubs
  # POST /originubs.json
  def create
    @originub = Originub.new(originub_params)

    respond_to do |format|
      if @originub.save
        format.html { redirect_to @originub, notice: 'Originub was successfully created.' }
        format.json { render :show, status: :created, location: @originub }
      else
        format.html { render :new }
        format.json { render json: @originub.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /originubs/1
  # PATCH/PUT /originubs/1.json
  def update
    respond_to do |format|
      if @originub.update(originub_params)
        format.html { redirect_to @originub, notice: 'Originub was successfully updated.' }
        format.json { render :show, status: :ok, location: @originub }
      else
        format.html { render :edit }
        format.json { render json: @originub.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /originubs/1
  # DELETE /originubs/1.json
  def destroy
    @originub.destroy
    respond_to do |format|
      format.html { redirect_to originubs_url, notice: 'Originub was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_originub
      @originub = Originub.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def originub_params
      params.require(:originub).permit(
         :latitude, :longitude, :cod_munic, :cod_cnes,
         :name, :address, :neighborhood, :city, :tel,
         :dsc_estrut_fisic_ambiencia, :dsc_adap_defic_fisic_idosos,
         :dsc_equipamentos, :dsc_medicamentos
      )
    end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]

  # GET /places
  # GET /places.json
  def index
    @places = Place.all
  end

  # GET /places/1
  # GET /places/1.json
  def show
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: 'Place was successfully created.' }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url, notice: 'Place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def get_locations
    require 'open-uri'
    require 'pry-byebug'
    url = url_maps(params)
    response = reponse_maps(open(url).read)

    # binding.pry
    @locations = response[:results]
  end

  def url_maps(params)
    url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=#{params[:latitude]},#{params[:longitude]}&radius=500&key=AIzaSyBPKkQD7imgDG1urIaEZ59a0u3tXNNYIcU"
  end

  def reponse_maps(http_call)
    JSON.parse(http_call, {:symbolize_names => true})
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(:name, :address, :latitude, :longitude)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/originubs_helper.rb
module OriginubsHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FindUbs</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>

    <div class='ui container'>
      <%= yield %>
    </div>
  </body>
</html>

app/views/originubs/_form.html.erb
<%= form_with(model: originub, local: true, class: 'ui form') do |form| %>
    <% if originub.errors.any? %>
      <div id="error_explanation">
        <h2>
        <%= pluralize(originub.errors.count, "error") %>
        prohibited this originub from being saved:
        </h2>

        <ul>
        <% originub.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

      <h4 class="ui dividing teal header">Dados da UBS</h4>
      <div class="tree fields">
        <div class="field">
          <%= form.label :cod_munic %>
          <%= form.number_field :cod_munic %>
        </div>

        <div class="field">
          <%= form.label :cod_cnes %>
          <%= form.number_field :cod_cnes %>
        </div>
      </div>

      <div class="field">
        <%= form.label :name %>
        <%= form.text_field :name %>
      </div>

      <div class="field">
        <%= form.label :address %>
        <%= form.text_field :address %>
      </div>

      <div class="field">
        <%= form.label :neighborhood %>
        <%= form.text_field :neighborhood %>
      </div>

      <div class="field">
        <%= form.label :city %>
        <%= form.text_field :city %>
      </div>

      <div class="field">
        <%= form.label :tel %>
        <%= form.text_field :tel %>
      </div>

      <h4 class="ui dividing teal header">Dados Geográfico</h4>
        <div class="two fields">
          <div class="field ">
            <%= form.label :latitude %>
            <%= form.text_field :latitude %>
          </div>

          <div class="field">
            <%= form.label :longitude %>
            <%= form.text_field :longitude %>
          </div>
       </div>

      <h4 class="ui dividing teal header">Pontuação</h4>
        <div class="field">
          <%= form.label :dsc_estrut_fisic_ambiencia %>
          <%= form.text_field :dsc_estrut_fisic_ambiencia %>
        </div>

        <div class="field">
          <%= form.label :dsc_adap_defic_fisic_idosos %>
          <%= form.text_field :dsc_adap_defic_fisic_idosos %>
        </div>

        <div class="field">
          <%= form.label :dsc_equipamentos %>
          <%= form.text_field :dsc_equipamentos %>
        </div>

        <div class="field">
          <%= form.label :dsc_medicamentos %>
          <%= form.text_field :dsc_medicamentos %>
        </div>

  <div class="actions">
  <%= form.submit %>
  </div>
<% end %>

app/views/originubs/_index.html.erb
<p id="notice"><%= notice %></p>

<h1>Originubs</h1>

<table>
  <thead>
    <tr>
      <th>Cod munic</th>
      <th>Name</th>
      <th>Address</th>
      <th>City</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @originubs.each do |originub| %>
      <tr>
        <td><%= originub.cod_munic %></td>
        <td><%= originub.name %></td>
        <td><%= originub.address %></td>
        <td><%= originub.city %></td>
        <td><%= link_to 'Show', originub %></td>
        <td><%= link_to 'Edit', edit_originub_path(originub) %></td>
        <td><%= link_to 'Destroy', originub, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Originub', new_originub_path %>

app/views/originubs/edit.html.erb
<h1>Editing Originub</h1>

<%= render 'form', originub: @originub %>
<br><br>
<%= link_to 'Show', @originub %> |
<%= link_to 'Back', originubs_path %>

app/views/originubs/index.html.erb
<div class="ui five column grid">
<% @originubs.each do |originub| %>
  <div class="column">

    <div class='ui fluid cards'>
      <div class='teal card'>
        <div class='content'>
          <div class='header'>
            <%= originub.city %>
          </div>

          <div class='meta'>
            <%= originub.name %>
          </div>

          <div class="description">
            <%= originub.address %><br>
            <%= originub.cod_munic %><br>
          </div>

          <div class="extra content">
            <%= link_to 'Show', originub, class: 'right floated' %>
            <br>
            <%= link_to 'Edit', edit_originub_path(originub), class: 'right floated' %>
          </div>
        </div>
      </div>
    </div>
    </div>
  <% end %>
</div>


<%= link_to 'New Originub', new_originub_path %>

app/views/originubs/new.html.erb
<h1>New Originub</h1>

<%= render 'form', originub: @originub %>

<br><br>
<%= link_to 'Back', originubs_path %>

app/views/originubs/show.html.erb
<p id="notice"><%= notice %></p>

<h4 class="ui dividing teal header">Dados da UBS</h4>
<p>
<strong>Cod munic:</strong>
<%= @originub.cod_munic %>
</p>

<p>
<strong>Cod cnes:</strong>
<%= @originub.cod_cnes %>
</p>

<p>
<strong>Name:</strong>
<%= @originub.name %>
</p>

<p>
<strong>Address:</strong>
<%= @originub.address %>
</p>

<p>
<strong>Neighborhood:</strong>
<%= @originub.neighborhood %>
</p>

<p>
<strong>City:</strong>
<%= @originub.city %>
</p>

<p>
<strong>Tel:</strong>
<%= @originub.tel %>
</p>

<h4 class="ui dividing teal header">Dados Geográfico</h4>
<p>
  <strong>Latitude:</strong>
  <%= @originub.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @originub.longitude %>
</p>

<h4 class="ui dividing teal header">Pontuação</h4>
<p>
<strong>Dsc estrut fisic ambiencia:</strong>
<%= @originub.dsc_estrut_fisic_ambiencia %>
</p>

<p>
<strong>Dsc adap defic fisic idosos:</strong>
<%= @originub.dsc_adap_defic_fisic_idosos %>
</p>

<p>
<strong>Dsc equipamentos:</strong>
<%= @originub.dsc_equipamentos %>
</p>

<p>
<strong>Dsc medicamentos:</strong>
<%= @originub.dsc_medicamentos %>
</p>



<%= link_to 'Edit', edit_originub_path(@originub) %> |
<%= link_to 'Back', originubs_path %>

app/views/places/_form.html.erb
<%= form_with(model: place, local: true, class: 'ui form') do |form| %>
  <% if place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(place.errors.count, "error") %> prohibited this place from being saved:</h2>

      <ul>
      <% place.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h4 class="ui dividing teal header">Dados</h4>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
<br>

app/views/places/edit.html.erb
<h1>Editing Place</h1>

<%= render 'form', place: @place %>

<%= link_to 'Show', @place %> |
<%= link_to 'Back', places_path %>

app/views/places/get_locations.js.erb
<% @locations.each do |loc| %>
  $('.location_results_list').append('<li><button data-attributes="<%= j loc.to_json.to_s %>"><%= loc[:name] %></button></li>');
<% end %>
createPlace();

app/views/places/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Places</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @places.each do |place| %>
      <tr>
        <td><%= place.name %></td>
        <td><%= place.address %></td>
        <td><%= place.latitude %></td>
        <td><%= place.longitude %></td>
        <td><%= link_to 'Show', place %></td>
        <td><%= link_to 'Edit', edit_place_path(place) %></td>
        <td><%= link_to 'Destroy', place, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
  <br>
  <%= content_tag :tbody, id: :places do %>
    <%= render @places %>
  <% end %>

</table>

<br><br>
<%= link_to 'New Place', new_place_path %>
<br><br>

<div>
  <%= content_tag :button, 'Obter Localização', class: 'ui small teal button get_location' %>
</div>

<br><br>
<div>
  <%= tag :div, class: 'location_results_list' %>
</div>

app/views/places/new.html.erb
<h1>New Place</h1>

<%= render 'form', place: @place %>

<%= link_to 'Back', places_path %>

app/views/places/show.html.erb
<p id="notice"><%= notice %></p>
<br>

<div class="ui internally celled grid">
  <div class="row">
    <div class="seven wide column">
      <div>
        <%= render 'shared/show_map' %>
      </div>
    </div>

    <div class="eight wide column">
        <p>
          <strong>Name:</strong>
          <%= @place.name %>
        </p>

        <p>
          <strong>Address:</strong>
          <%= @place.address %>
        </p>

        <p>
          <strong>Latitude:</strong>
          <%= @place.latitude %>
        </p>

        <p>
          <strong>Longitude:</strong>
          <%= @place.longitude %>
        </p>
    </div>
  </div>
</div>


<%= link_to 'Edit', edit_place_path(@place) %> |
<%= link_to 'Back', places_path %>

app/views/shared/_navbar.html.erb
<div class='ui teal inverted menu'>
  <div class='ui container'>
    <div class='ui center aligned icon header'>
      <i class='ambulance icon'></i>
        Unidade Basica de Saúde

    </div>
  </div>
</div>

app/views/shared/_show_map.html.erb
<%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@place.latitude}%2C#{@place.longitude}" %>